model:
  base_learning_rate: 6.0e-06 # 1.5e-04
  scale_lr: False
  # empty_params_only: True # disable this means finetuning all parameters
  # sd_checkpoint: /project/llmsvgen/share/shared_ckpts/StableDiffusion/v2-1_512-ema-pruned.ckpt
  # pretrained_checkpoint: /project/llmsvgen/share/shared_ckpts/VideoCrafter/VideoCrafter2-Text2Video-512/model.ckpt
  target: src.base.iddpm3d.LatentDiffusion
  params:
    # loss_type: l1
    log_every_t: 200
    first_stage_key: video
    cond_stage_key: caption
    # cond_stage_trainable: false
    cond_stage_trainable: true
    conditioning_key: crossattn_stdit
    image_size: # TO CHECK 
    - 32
    - 32
    channels: 4
    scale_by_std: false
    scale_factor: 0.18215
    use_ema: false
    uncond_type: empty_seq
    monitor: val/loss_simple_ema
    encoder_type: 3d
    use_scale: true
    scale_b: 0.7 # adapt to videocrafter-v2

    diffusion_scheduler_config:
      target: src.base.iddpm3d.OpenSoraScheduler
      params: 
        timesteps: 1000
        linear_start: 0.00085
        linear_end: 0.012

    unet_config:
      target: src.opensora.models.stdit.stdit.STDiT_XL_2
      params:
        space_scale: 0.5
        time_scale: 1.0
        # from_pretrained: "/project/llmsvgen/share/opensora_ckpt/stage4/last/model_ckpt.pt"
        from_pretrained: "/disk8/yazhou/check-base/opensora_ckpt/model_ckpt.pt"
        enable_flashattn: True
        enable_layernorm_kernel: False
        input_size:
        - 16
        - 32
        - 32 
    first_stage_config:
      target: src.lvdm.opensoravae.VideoAutoencoderKL
      params:
          from_pretrained: stabilityai/sd-vae-ft-ema
          micro_batch_size: 4
    cond_stage_config:
      target: src.opensora.models.text_encoder.t5.T5Encoder
      params:
        from_pretrained: "DeepFloyd/t5-v1_1-xxl"
        model_max_length: 120
        shardformer: False # TODO 

data:
  target: src.data.lightning_data.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 16
    wrap: false
    train:
      target: src.data.datasets.DatasetFromCSV
      params:
        # csv_path: /project/llmsvgen/share/opensora_datafile/artgrid_caption_long_base.csv
        csv_path: /disk8/yazhou/Dataset/artgrid/artgrid_caption_long_base_disk8.csv
        data_root: /disk8/yazhou/Dataset/artgrid
        resolution: [256, 256]
        video_length: 16
        frame_interval: 4
        train: True
    validation:
      target: src.data.datasets.DatasetFromCSV
      params:
        # csv_path: /project/llmsvgen/share/opensora_datafile/artgrid_caption_long_base.csv
        csv_path: /disk8/yazhou/Dataset/artgrid/artgrid_caption_long_base_disk8.csv
        data_root: /disk8/yazhou/Dataset/artgrid
        resolution: [256, 256]
        video_length: 16
        frame_interval: 4
        train: False

lightning:
  callbacks:
    image_logger:
      target: src.utils.callbacks.ImageLogger
      params:
        batch_frequency: 200
        max_images: 6
        to_local: True # save videos into files
        log_images_kwargs:
          unconditional_guidance_scale: 12 # need this, otherwise it is grey
        save_dir: ./results
    metrics_over_trainsteps_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        filename: "{epoch:06}-{step:09}"
        save_weights_only: False
        every_n_epochs: null
        every_n_train_steps: 1000
  trainer:
    benchmark: True
    num_workers: 32
    num_nodes: 1
    accumulate_grad_batches: 1
    max_epochs: 2000
    precision: bf16 # training precision
  # modelcheckpoint:
  #   target: pytorch_lightning.callbacks.ModelCheckpoint
  #   params:
  #     every_n_epochs: 1
  #     filename: "{epoch:04}-{step:06}"